inherit_gem:
  retrieva-cop:
    - "config/rubocop.yml"
    # comment unless use rails cops
    - "config/rails.yml"
    # comment unless use rspec cops
    - "config/rspec.yml"

RSpec/ExampleLength:
  Exclude:
    - spec/system/*
    - spec/models/*

RSpec/MultipleExpectations:
  Exclude:
  - spec/system/*

Metrics/ClassLength:
  Max: 200

Metrics/AbcSize:
  Max: 30
  Exclude:
    - app/controllers/tasks_controller.rb

Metrics/BlockLength:
  Exclude:
    - db/schema.rb
    - spec/*/*.rb
    - config/*/*.rb

Style/StringLiterals:
  Exclude:
    - db/schema.rb

Style/NumericLiterals:
  Exclude:
    - db/schema.rb

Style/WordArray:
  Exclude:
    - db/schema.rb

AllCops:
  TargetRubyVersion: 3.1
  # comment unless use rails cops
  TargetRailsVersion: 7.0
  Exclude:
    - bin/bundle
    - vendor/**/*
