inherit_gem:
  retrieva-cop:
    - "config/rubocop.yml"
    # comment unless use rails cops
    - "config/rails.yml"
    # comment unless use rspec cops
    - "config/rspec.yml"

RSpec/ExampleLength:
  Exclude:
    - spec/system/*

RSpec/MultipleExpectations:
  Exclude:
  - spec/system/*

AllCops:
  TargetRubyVersion: 3.1
  # comment unless use rails cops
  TargetRailsVersion: 7.0
  Exclude:
    - bin/bundle
    - vendor/**/*
