default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode
  username: task_app
  password:       
  host: localhost

development:
  <<: *default
  database: task_app_development

test:
  <<: *default
  database: github-actions
  password: <%= ENV["POSTGRES_PASSWORD"] %>

test:
  <<: *default
  database: github-actions
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

production:
  <<: *default
  password: <%= ENV['TASK_APP_DATABASE_PASSWORD'] %>