default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  database: task_app_development

test:
  <<: *default
  database: task_app_test

#Herokuデプロイ時に再度見直す
production:
  <<: *default
  database: task_app_production
  username: task_app
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>